#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "component-metrics-example"
version = "0.1.0"
authors = ["Andrew Steurer <94206073+asteurer@users.noreply.github.com>"]
description = "An application that generates CPU usage and allocates some memory"

[[trigger.http]]
route = "/..."
component = "component-metrics-example"

[component.component-metrics-example]
source = "target/wasm32-wasip1/release/component_metrics_example.wasm"
allowed_outbound_hosts = []
[component.component-metrics-example.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
